### ISSUE TITLE
zip dependency need to update

### ISSUE THREAD

**Issue by Kai5174** [neelpatel05/bruteforce-zip#1]
Hi, as i've clone this repo and found the following denpendency need to be updated.

![image](https://user-images.githubusercontent.com/20858666/107318730-6383e300-6ad8-11eb-9511-8aee4768ae61.png)

as Repo `https://github.com/keyas/zip` is no longer exists, we can use origin Repo `https://github.com/alexmullins/zip` instead

**Comment by neelpatel05** [comment]
Hey,
Please send me a pull request. Will do a review and merge it. Thank you very much.
